name: Release the lib to Hackage

on:
  push:
    branches:
      - supermajor
      - major
      - minor
      - patch

concurrency:
  group: release
  cancel-in-progress: false

jobs:

  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format.yaml@v3
    secrets: inherit
  
  test:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/check.yaml@v3
    secrets: inherit
  
  release:
    needs:
      - format
      - test
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/release.yaml@v3
    secrets: inherit
    with:
      prefix-tag-with-v: false
      docs: false
